import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const ROOT = dirname(fileURLToPath(import.meta.url));

function stars(rating) {
  return rating >= 4.8 ? '★★★★★' : '★★★★☆';
}

function buildSection(c) {
  const adBadge = c.lang === 'it' ? 'Ann.' : 'Ad';
  const btnDir  = c.lang === 'it' ? 'Indicazioni' : 'Directions';
  const btnCall = c.lang === 'it' ? 'Chiama' : 'Call';
  const btnWeb  = c.lang === 'it' ? 'Sito web' : 'Website';

  return `\n<!-- ADS SHOWCASE -->\n<style>.ads-showcase-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:40px;align-items:start}@media(max-width:767px){.ads-showcase-grid{grid-template-columns:1fr}}</style>\n<section style="background:${c.bgColor};padding:88px 0;position:relative">\n  <div style="max-width:1320px;margin:0 auto;padding:0 24px">\n    <div style="text-align:center;margin-bottom:52px">\n      <div style="display:inline-flex;align-items:center;gap:8px;background:${c.badgeBg};border:1px solid ${c.sectorColor}44;border-radius:100px;padding:6px 16px;margin-bottom:18px">\n        <div style="width:7px;height:7px;border-radius:50%;background:${c.sectorColor}"></div>\n        <span style="font-family:'Poppins',sans-serif;font-size:0.72rem;font-weight:600;color:${c.sectorColor};letter-spacing:0.09em;text-transform:uppercase">${c.badgeLabel}</span>\n      </div>\n      <h2 style="font-family:'Archivo Black',sans-serif;font-size:clamp(1.7rem,3.8vw,2.5rem);color:#0A0A0A;margin:0 0 16px;line-height:1.18">${c.hookLine1}<br>${c.hookLine2} <em style="font-style:normal;color:${c.sectorColor}">"${c.hookEm}"</em></h2>\n      <p style="font-family:'Poppins',sans-serif;font-size:0.97rem;color:rgba(10,10,10,0.62);max-width:520px;margin:0 auto;line-height:1.7">${c.hookSub}</p>\n    </div>\n    <div class="ads-showcase-grid">\n      <div style="background:#fff;border-radius:16px;box-shadow:0 4px 20px rgba(0,0,0,0.09),0 1px 4px rgba(0,0,0,0.05);overflow:hidden;border:1px solid rgba(0,0,0,0.06)">\n        <div style="padding:11px 14px;background:#fff;border-bottom:1px solid #f0f0f0;display:flex;align-items:center;gap:9px">\n          <svg width="20" height="20" viewBox="0 0 24 24" fill="none"><path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4"/><path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853"/><path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05"/><path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335"/></svg>\n          <div style="flex:1;background:#f1f3f4;border-radius:22px;padding:6px 14px;font-family:Arial,sans-serif;font-size:13px;color:#202124;overflow:hidden;white-space:nowrap;text-overflow:ellipsis">${c.searchQuery}</div>\n        </div>\n        <div style="padding:13px 14px 0">\n          <div style="display:flex;align-items:center;gap:6px;margin-bottom:3px">\n            <span style="font-size:10px;font-family:Arial,sans-serif;color:#0d652d;border:1px solid #0d652d;border-radius:3px;padding:1px 4px;font-weight:500">${adBadge}</span>\n            <span style="font-size:11.5px;font-family:Arial,sans-serif;color:#4d5156">${c.bizUrl}</span>\n          </div>\n          <div style="font-size:17px;font-family:Arial,sans-serif;color:#1a0dab;margin-bottom:3px;line-height:1.3">${c.headline}</div>\n          <div style="display:flex;align-items:center;gap:3px;margin-bottom:4px">\n            <span style="color:#f5a623;font-size:12px;letter-spacing:-0.5px">${stars(c.rating)}</span>\n            <span style="font-size:11.5px;font-family:Arial,sans-serif;color:#4d5156">${c.ratingDisplay} · ${c.reviewCount}</span>\n          </div>\n          <div style="font-size:12.5px;font-family:Arial,sans-serif;color:#4d5156;line-height:1.58">${c.desc}</div>\n          <div style="display:flex;flex-wrap:wrap;gap:6px;margin-top:8px;padding-bottom:13px">${c.sitelinks.map(s=>`<span style="font-size:11.5px;font-family:Arial,sans-serif;color:#1a0dab;border:1px solid #dadce0;border-radius:4px;padding:3px 9px">${s}</span>`).join('')}</div>\n        </div>\n        <div style="padding:0 14px 12px;border-top:1px solid #f0f0f0">\n          <div style="opacity:0.32;margin-top:10px"><div style="font-size:11px;font-family:Arial,sans-serif;color:#4d5156;margin-bottom:2px">${c.org1url}</div><div style="font-size:15px;font-family:Arial,sans-serif;color:#1a0dab;margin-bottom:2px">${c.org1title}</div><div style="font-size:12px;font-family:Arial,sans-serif;color:#4d5156">${c.org1desc}</div></div>\n          <div style="opacity:0.14;margin-top:7px"><div style="font-size:11px;font-family:Arial,sans-serif;color:#4d5156;margin-bottom:2px">${c.org2url}</div><div style="font-size:15px;font-family:Arial,sans-serif;color:#1a0dab;margin-bottom:2px">${c.org2title}</div><div style="font-size:12px;font-family:Arial,sans-serif;color:#4d5156">${c.org2desc}</div></div>\n        </div>\n      </div>\n      <div style="background:#fff;border-radius:16px;box-shadow:0 4px 20px rgba(0,0,0,0.09),0 1px 4px rgba(0,0,0,0.05);overflow:hidden;border:1px solid rgba(0,0,0,0.06)">\n        <div style="height:185px;position:relative;overflow:hidden;background:#e8eef4">\n          <svg width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" style="position:absolute;inset:0"><rect width="100%" height="100%" fill="#e8eef4"/><rect x="0%" y="24%" width="100%" height="11%" fill="#fff"/><rect x="44%" y="0%" width="7%" height="100%" fill="#fff"/><rect x="0%" y="62%" width="100%" height="8%" fill="#f5f5f5"/><rect x="73%" y="0%" width="5%" height="100%" fill="#f5f5f5"/><rect x="18%" y="0%" width="5%" height="100%" fill="#f5f5f5"/><rect x="5%" y="5%" width="11%" height="18%" fill="#d9e3ea" rx="2"/><rect x="5%" y="72%" width="11%" height="18%" fill="#d9e3ea" rx="2"/><rect x="53%" y="5%" width="17%" height="17%" fill="#d9e3ea" rx="2"/><rect x="53%" y="72%" width="17%" height="18%" fill="#d9e3ea" rx="2"/><rect x="79%" y="5%" width="14%" height="14%" fill="#d9e3ea" rx="2"/><rect x="25%" y="72%" width="13%" height="18%" fill="#d9e3ea" rx="2"/></svg>\n          <div style="position:absolute;left:47%;top:35%;transform:translate(-50%,-100%)"><svg width="28" height="36" viewBox="0 0 32 42" fill="none"><path d="M16 0C7.163 0 0 7.163 0 16c0 13 16 26 16 26S32 29 32 16C32 7.163 24.837 0 16 0z" fill="${c.pinColor}"/><circle cx="16" cy="16" r="7" fill="#fff"/></svg></div>\n          <div style="position:absolute;top:8px;right:8px;background:rgba(255,255,255,0.92);border-radius:4px;padding:3px 8px;box-shadow:0 1px 4px rgba(0,0,0,0.14)"><span style="font-family:Arial,sans-serif;font-size:10px;font-weight:700;color:#4285F4">Google</span><span style="font-family:Arial,sans-serif;font-size:10px;color:#4d5156"> Maps</span></div>\n        </div>\n        <div style="padding:16px">\n          <div style="font-size:16px;font-family:Arial,sans-serif;font-weight:600;color:#202124;margin-bottom:3px">${c.mapBizName}</div>\n          <div style="font-size:12.5px;font-family:Arial,sans-serif;color:#4d5156;margin-bottom:6px">${c.mapCategory}</div>\n          <div style="display:flex;align-items:center;gap:4px;margin-bottom:8px"><span style="font-size:13px;font-family:Arial,sans-serif;font-weight:600;color:#202124">${c.ratingDisplay}</span><span style="color:#f5a623;font-size:12px;letter-spacing:-0.5px">${stars(c.rating)}</span><span style="font-size:11.5px;font-family:Arial,sans-serif;color:#70757a">${c.mapReviewLabel}</span></div>\n          <div style="display:flex;align-items:center;gap:6px;margin-bottom:14px"><svg width="13" height="13" viewBox="0 0 24 24" fill="#70757a"><path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5s1.12-2.5 2.5-2.5 2.5 1.12 2.5 2.5-1.12 2.5-2.5 2.5z"/></svg><span style="font-size:12px;font-family:Arial,sans-serif;color:#4d5156">${c.mapAddr}</span></div>\n          <div style="display:flex;gap:8px">\n            <button style="flex:1;background:${c.btnBg};color:${c.pinColor};border:none;border-radius:20px;padding:8px 10px;font-size:11.5px;font-family:Arial,sans-serif;font-weight:600;cursor:pointer">${btnDir}</button>\n            <button style="flex:1;background:${c.btnBg};color:${c.pinColor};border:none;border-radius:20px;padding:8px 10px;font-size:11.5px;font-family:Arial,sans-serif;font-weight:600;cursor:pointer">${btnCall}</button>\n            <button style="flex:1;background:#f1f3f4;color:#4d5156;border:none;border-radius:20px;padding:8px 10px;font-size:11.5px;font-family:Arial,sans-serif;font-weight:600;cursor:pointer">${btnWeb}</button>\n          </div>\n        </div>\n      </div>\n    </div>\n    <div style="text-align:center;background:#fff;border-radius:20px;padding:36px;border:1px solid rgba(0,0,0,0.07);box-shadow:0 2px 12px rgba(0,0,0,0.05)">\n      <p style="font-family:'Archivo Black',sans-serif;font-size:1.22rem;color:#0A0A0A;margin:0 0 8px">${c.closingH}</p>\n      <p style="font-family:'Poppins',sans-serif;font-size:0.92rem;color:rgba(10,10,10,0.62);margin:0 0 22px">${c.closingP}</p>\n      <a href="https://calendly.com/nicoladimattia8/30min" onclick="Calendly.initPopupWidget({url:'https://calendly.com/nicoladimattia8/30min?month=2026-05'});return false;" style="display:inline-flex;align-items:center;gap:8px;background:${c.sectorColor};color:#fff;border-radius:100px;padding:14px 30px;font-family:'Poppins',sans-serif;font-weight:600;font-size:0.88rem;text-decoration:none" onmouseover="this.style.opacity='0.88'" onmouseout="this.style.opacity='1'">${c.ctaText}</a>\n    </div>\n  </div>\n</section>\n`;
}

const pages = [
  // ── ITALIAN ─────────────────────────────────────────────────────────────
  {
    file: 'dentist/index.html',
    insertBefore: '<section class="section" id="metodo">',
    lang: 'it', sectorColor: '#1a73e8', bgColor: '#f0f4ff', badgeBg: '#e8eeff',
    pinColor: '#1a73e8', btnBg: '#e8f0fe',
    badgeLabel: 'Google Ads · Anteprima Reale',
    hookLine1: 'Questo è ciò che vede il tuo potenziale paziente',
    hookLine2: 'quando cerca su Google', hookEm: 'dentista Roma',
    hookSub: 'I tuoi concorrenti hanno già il loro annuncio lì. Il tuo studio potrebbe apparire in prima posizione già da domani.',
    searchQuery: 'dentista Roma Prati',
    bizUrl: 'www.studioferretti.it',
    headline: 'Studio Dentistico Ferretti – Sorridi con Fiducia',
    rating: 4.9, ratingDisplay: '4,9', reviewCount: '127 recensioni',
    desc: 'Visite, pulizie e sbiancamento a Roma Prati. Prima visita gratuita — prenota online in 60 secondi.',
    sitelinks: ['Prima Visita Gratuita', 'Implantologia', 'Sbiancamento', 'Prenota Online'],
    org1url: 'www.dentista-roma.it', org1title: 'Dentista Roma – Studio Associato', org1desc: 'Dentisti a Roma. Preventivi gratuiti online...',
    org2url: 'www.dentistaprati.com', org2title: 'Dentista Prati Roma – Prenota Ora', org2desc: 'Studio dentistico nel quartiere Prati...',
    mapBizName: 'Studio Dentistico Ferretti', mapCategory: 'Dentista · <span style="color:#188038">Aperto</span> · Chiude alle 19:00',
    mapReviewLabel: '(127 recensioni)', mapAddr: 'Via Cola di Rienzo 45, Roma',
    closingH: 'Il tuo studio potrebbe apparire qui.',
    closingP: 'Configuriamo tutto noi — tu aspetta i pazienti.',
    ctaText: 'Prenota una call gratuita →',
  },
  {
    file: 'ristorante/index.html',
    insertBefore: '<section class="section" id="metodo">',
    lang: 'it', sectorColor: '#e8471a', bgColor: '#fff4f0', badgeBg: '#fde8e0',
    pinColor: '#e8471a', btnBg: '#fde8e0',
    badgeLabel: 'Google Ads · Anteprima Reale',
    hookLine1: 'Questo è ciò che vede il tuo potenziale cliente',
    hookLine2: 'quando cerca su Google', hookEm: 'ristorante Milano',
    hookSub: 'I tuoi concorrenti stanno già investendo in Google Ads. Il tuo locale potrebbe apparire qui già da domani sera.',
    searchQuery: 'ristorante Milano Navigli',
    bizUrl: 'www.trattoriadasergio.it',
    headline: 'Trattoria da Sergio – Cucina Milanese dal 1987',
    rating: 4.7, ratingDisplay: '4,7', reviewCount: '204 recensioni',
    desc: 'Ristorante tipico ai Navigli di Milano. Prenota il tuo tavolo online — menu degustazione disponibile ogni sera.',
    sitelinks: ['Prenota Tavolo', 'Menu del Giorno', 'Sala Privata', 'Come Raggiungerci'],
    org1url: 'www.ristoranti-navigli.it', org1title: 'Ristoranti Navigli Milano – I Migliori', org1desc: 'Scopri i migliori ristoranti ai Navigli...',
    org2url: 'www.migliorinavigli.com', org2title: 'Navigli Milano – Cucina Tradizionale', org2desc: 'Ristoranti tipici milanesi. Prenota ora...',
    mapBizName: 'Trattoria da Sergio', mapCategory: 'Ristorante · <span style="color:#188038">Aperto</span> · Chiude alle 23:00',
    mapReviewLabel: '(204 recensioni)', mapAddr: 'Via dei Navigli 18, Milano',
    closingH: 'Il tuo ristorante potrebbe apparire qui.',
    closingP: 'Configuriamo tutto noi — tu prepara i tavoli.',
    ctaText: 'Prenota una call gratuita →',
  },
  {
    file: 'avvocati/index.html',
    insertBefore: '<section class="section" id="metodo">',
    lang: 'it', sectorColor: '#1a237e', bgColor: '#f0f1ff', badgeBg: '#e8eaff',
    pinColor: '#1a237e', btnBg: '#e8eaff',
    badgeLabel: 'Google Ads · Anteprima Reale',
    hookLine1: 'Questo è ciò che vede il tuo potenziale cliente',
    hookLine2: 'quando cerca su Google', hookEm: 'avvocato Torino',
    hookSub: 'I tuoi concorrenti hanno già il loro annuncio lì. Il tuo studio legale potrebbe apparire in prima posizione già da domani.',
    searchQuery: 'avvocato divorzio Torino',
    bizUrl: 'www.studiolegale-marchetti.it',
    headline: 'Avv. Marchetti – Diritto di Famiglia Torino',
    rating: 4.8, ratingDisplay: '4,8', reviewCount: '89 recensioni',
    desc: 'Separazione, divorzio e affido minori a Torino. Consulenza gratuita di 30 minuti — avvocati specializzati dal 2001.',
    sitelinks: ['Consulenza Gratuita', 'Separazione', 'Affido Minori', 'Contattaci'],
    org1url: 'www.avvocato-torino.it', org1title: 'Avvocati Torino – Studio Legale', org1desc: 'Avvocati specializzati a Torino...',
    org2url: 'www.legale-torino.com', org2title: 'Studio Legale Torino – Diritto Civile', org2desc: 'Consulenza legale professionale...',
    mapBizName: 'Studio Legale Marchetti', mapCategory: 'Studio Legale · <span style="color:#188038">Aperto</span> · Chiude alle 18:30',
    mapReviewLabel: '(89 recensioni)', mapAddr: 'Corso Vittorio Emanuele II 112, Torino',
    closingH: 'Il tuo studio legale potrebbe apparire qui.',
    closingP: 'Configuriamo tutto noi — tu pensa ai tuoi clienti.',
    ctaText: 'Prenota una call gratuita →',
  },
  {
    file: 'idraulico/index.html',
    insertBefore: '<section class="section" id="metodo">',
    lang: 'it', sectorColor: '#2e7d32', bgColor: '#f0f7f0', badgeBg: '#e8f5e9',
    pinColor: '#2e7d32', btnBg: '#e8f5e9',
    badgeLabel: 'Google Ads · Anteprima Reale',
    hookLine1: 'Questo è ciò che vede il tuo potenziale cliente',
    hookLine2: 'quando cerca su Google', hookEm: 'idraulico Bologna',
    hookSub: 'I tuoi concorrenti stanno già ricevendo chiamate dai tuoi clienti. Il tuo nome potrebbe apparire al primo posto già domani.',
    searchQuery: 'idraulico emergenza Bologna',
    bizUrl: 'www.idraulicopronto-bo.it',
    headline: 'Idraulico Pronto Bologna – Intervento in 30 Min',
    rating: 4.9, ratingDisplay: '4,9', reviewCount: '156 recensioni',
    desc: 'Perdite, intasamenti e caldaie a Bologna. Disponibile 24/7 — preventivo gratuito immediato, senza sorprese.',
    sitelinks: ['Chiama Ora', 'Emergenze 24/7', 'Preventivo Gratis', 'Area Servizio'],
    org1url: 'www.idraulici-bologna.it', org1title: 'Idraulici Bologna – Pronto Intervento', org1desc: 'Idraulici a Bologna disponibili H24...',
    org2url: 'www.pronto-idraulico.com', org2title: 'Idraulico Bologna – Interventi Rapidi', org2desc: 'Riparazioni impianti idraulici...',
    mapBizName: 'Idraulico Pronto Bologna', mapCategory: 'Idraulico · <span style="color:#188038">Aperto</span> · Disponibile 24/7',
    mapReviewLabel: '(156 recensioni)', mapAddr: 'Via Zamboni 22, Bologna',
    closingH: 'La tua attività potrebbe apparire qui.',
    closingP: 'Configuriamo tutto noi — tu pensa alle riparazioni.',
    ctaText: 'Prenota una call gratuita →',
  },
  {
    file: 'palestra/index.html',
    insertBefore: '<section class="section" id="metodo">',
    lang: 'it', sectorColor: '#7b1fa2', bgColor: '#f9f0ff', badgeBg: '#f3e5ff',
    pinColor: '#7b1fa2', btnBg: '#f3e5ff',
    badgeLabel: 'Google Ads · Anteprima Reale',
    hookLine1: 'Questo è ciò che vede il tuo potenziale cliente',
    hookLine2: 'quando cerca su Google', hookEm: 'palestra Firenze',
    hookSub: 'I tuoi concorrenti stanno già acquisendo nuovi iscritti. La tua palestra potrebbe apparire al primo posto già da domani.',
    searchQuery: 'palestra Firenze centro',
    bizUrl: 'www.fitcenter-firenze.it',
    headline: 'FitCenter Firenze – Allenati nel Centro Storico',
    rating: 4.6, ratingDisplay: '4,6', reviewCount: '312 recensioni',
    desc: 'Palestra attrezzata a Firenze Centro. Prova gratuita 7 giorni — personal trainer incluso nel primo mese.',
    sitelinks: ['Prova 7 Giorni Gratis', 'Corsi Fitness', 'Personal Trainer', 'Abbonamenti'],
    org1url: 'www.palestre-firenze.it', org1title: 'Palestre Firenze – Abbonamenti e Corsi', org1desc: 'Le migliori palestre di Firenze...',
    org2url: 'www.fitness-firenze.com', org2title: 'Fitness Center Firenze – Prenota Ora', org2desc: 'Centro fitness nel cuore di Firenze...',
    mapBizName: 'FitCenter Firenze', mapCategory: 'Palestra · <span style="color:#188038">Aperto</span> · Chiude alle 22:00',
    mapReviewLabel: '(312 recensioni)', mapAddr: 'Via dei Servi 42, Firenze',
    closingH: 'La tua palestra potrebbe apparire qui.',
    closingP: 'Configuriamo tutto noi — tu allena i tuoi clienti.',
    ctaText: 'Prenota una call gratuita →',
  },
  {
    file: 'estetica/index.html',
    insertBefore: '<section class="section" id="metodo">',
    lang: 'it', sectorColor: '#c2185b', bgColor: '#fff0f5', badgeBg: '#ffe8f1',
    pinColor: '#c2185b', btnBg: '#ffe8f1',
    badgeLabel: 'Google Ads · Anteprima Reale',
    hookLine1: 'Questo è ciò che vede la tua potenziale cliente',
    hookLine2: 'quando cerca su Google', hookEm: 'centro estetico Napoli',
    hookSub: 'I tuoi concorrenti hanno già il loro annuncio attivo. Il tuo centro estetico potrebbe apparire al primo posto già domani.',
    searchQuery: 'centro estetico Napoli Chiaia',
    bizUrl: 'www.beautylabchiaia.it',
    headline: 'Beauty Lab Chiaia – Trattamenti Viso e Corpo',
    rating: 4.8, ratingDisplay: '4,8', reviewCount: '178 recensioni',
    desc: 'Centro estetico a Napoli Chiaia. Trattamenti viso, laser e massaggi — prenota online in 2 minuti.',
    sitelinks: ['Prenota Ora', 'Laser Depilazione', 'Trattamenti Viso', 'Lista Prezzi'],
    org1url: 'www.estetica-napoli.it', org1title: 'Centri Estetici Napoli – I Migliori', org1desc: 'Centri estetici a Napoli con recensioni...',
    org2url: 'www.chiaia-beauty.com', org2title: 'Beauty Center Chiaia – Trattamenti', org2desc: 'Trattamenti estetici nel cuore di Napoli...',
    mapBizName: 'Beauty Lab Chiaia', mapCategory: 'Centro Estetico · <span style="color:#188038">Aperto</span> · Chiude alle 20:00',
    mapReviewLabel: '(178 recensioni)', mapAddr: 'Via Chiaia 88, Napoli',
    closingH: 'Il tuo centro estetico potrebbe apparire qui.',
    closingP: 'Configuriamo tutto noi — tu cura le tue clienti.',
    ctaText: 'Prenota una call gratuita →',
  },
  {
    file: 'fisioterapia/index.html',
    insertBefore: '<section class="section" id="metodo">',
    lang: 'it', sectorColor: '#00796b', bgColor: '#f0faf8', badgeBg: '#e0f5f3',
    pinColor: '#00796b', btnBg: '#e0f5f3',
    badgeLabel: 'Google Ads · Anteprima Reale',
    hookLine1: 'Questo è ciò che vede il tuo potenziale paziente',
    hookLine2: 'quando cerca su Google', hookEm: 'fisioterapista Milano',
    hookSub: 'I tuoi concorrenti stanno già ricevendo nuove prenotazioni. Il tuo studio potrebbe apparire in prima posizione già da domani.',
    searchQuery: 'fisioterapista Milano Brera',
    bizUrl: 'www.studiofisiobrera.it',
    headline: 'Studio Fisio Brera – Fisioterapia e Osteopatia',
    rating: 4.9, ratingDisplay: '4,9', reviewCount: '94 recensioni',
    desc: 'Fisioterapia, osteopatia e riabilitazione a Milano Brera. Prima seduta scontata — prenota online oggi stesso.',
    sitelinks: ['Prima Seduta Scontata', 'Osteopatia', 'Riabilitazione', 'Prenota Online'],
    org1url: 'www.fisioterapia-milano.it', org1title: 'Fisioterapia Milano – Studio Specializzato', org1desc: 'Fisioterapisti a Milano con prenotazione...',
    org2url: 'www.brera-fisio.com', org2title: 'Osteopatia Milano Brera – Centro Salute', org2desc: 'Fisioterapia e osteopatia nel centro...',
    mapBizName: 'Studio Fisio Brera', mapCategory: 'Fisioterapista · <span style="color:#188038">Aperto</span> · Chiude alle 19:00',
    mapReviewLabel: '(94 recensioni)', mapAddr: 'Corso Garibaldi 78, Milano',
    closingH: 'Il tuo studio potrebbe apparire qui.',
    closingP: 'Configuriamo tutto noi — tu pensa ai tuoi pazienti.',
    ctaText: 'Prenota una call gratuita →',
  },
  {
    file: 'hotel/index.html',
    insertBefore: '<section class="section" id="metodo">',
    lang: 'it', sectorColor: '#e65100', bgColor: '#fff5f0', badgeBg: '#ffe8d6',
    pinColor: '#e65100', btnBg: '#ffe8d6',
    badgeLabel: 'Google Ads · Anteprima Reale',
    hookLine1: 'Questo è ciò che vede il tuo potenziale ospite',
    hookLine2: 'quando cerca su Google', hookEm: 'hotel Roma',
    hookSub: 'I tuoi concorrenti stanno già ricevendo prenotazioni dirette. Il tuo hotel potrebbe apparire al primo posto già da domani.',
    searchQuery: 'hotel Roma centro storico',
    bizUrl: 'www.hotelforiimperiali.it',
    headline: 'Hotel Fori Imperiali – Nel Cuore di Roma',
    rating: 4.7, ratingDisplay: '4,7', reviewCount: '521 recensioni',
    desc: 'Hotel 4 stelle a Roma Centro Storico. Colazione inclusa, WiFi gratuito — prenota diretto e risparmi il 20%.',
    sitelinks: ['Prenota Diretto', 'Offerte Speciali', 'Camere e Tariffe', 'Dove Siamo'],
    org1url: 'www.hotel-roma-centro.it', org1title: 'Hotel Roma Centro – Migliori Offerte', org1desc: 'I migliori hotel nel centro di Roma...',
    org2url: 'www.romahotel24.com', org2title: 'Hotel Roma – Prenota al Miglior Prezzo', org2desc: 'Alberghi a Roma con colazione inclusa...',
    mapBizName: 'Hotel Fori Imperiali', mapCategory: 'Hotel ★★★★ · <span style="color:#188038">Aperto</span> · Reception 24 ore',
    mapReviewLabel: '(521 recensioni)', mapAddr: 'Via dei Fori Imperiali 15, Roma',
    closingH: 'Il tuo hotel potrebbe apparire qui.',
    closingP: 'Configuriamo tutto noi — tu prepara l\'accoglienza.',
    ctaText: 'Prenota una call gratuita →',
  },
  {
    file: 'immobiliare/index.html',
    insertBefore: '<section class="section" id="metodo">',
    lang: 'it', sectorColor: '#f57f17', bgColor: '#fffaf0', badgeBg: '#fff3e0',
    pinColor: '#f57f17', btnBg: '#fff3e0',
    badgeLabel: 'Google Ads · Anteprima Reale',
    hookLine1: 'Questo è ciò che vede il tuo potenziale cliente',
    hookLine2: 'quando cerca su Google', hookEm: 'agenzia immobiliare Venezia',
    hookSub: 'I tuoi concorrenti stanno già raccogliendo lead qualificati. La tua agenzia potrebbe apparire al primo posto già da domani.',
    searchQuery: 'agenzia immobiliare Venezia',
    bizUrl: 'www.immobilvenezia.it',
    headline: 'ImmobilVenezia – Appartamenti e Ville a Venezia',
    rating: 4.8, ratingDisplay: '4,8', reviewCount: '67 recensioni',
    desc: 'Agenzia immobiliare a Venezia dal 1998. Acquisto, vendita e affitto — valutazione gratuita del tuo immobile.',
    sitelinks: ['Valutazione Gratuita', 'Appartamenti', 'Ville e Lusso', 'Chi Siamo'],
    org1url: 'www.case-venezia.it', org1title: 'Case Venezia – Compra e Affitto', org1desc: 'Immobili a Venezia. Tutte le proposte...',
    org2url: 'www.venezia-homes.com', org2title: 'Venezia Homes – Agenzia Immobiliare', org2desc: 'Appartamenti e ville a Venezia e Mestre...',
    mapBizName: 'ImmobilVenezia Realty', mapCategory: 'Agenzia Immobiliare · <span style="color:#188038">Aperto</span> · Chiude alle 18:00',
    mapReviewLabel: '(67 recensioni)', mapAddr: 'Campo San Luca 4516, Venezia',
    closingH: 'La tua agenzia potrebbe apparire qui.',
    closingP: 'Configuriamo tutto noi — tu pensa ai tuoi immobili.',
    ctaText: 'Prenota una call gratuita →',
  },

  // ── ENGLISH ──────────────────────────────────────────────────────────────
  {
    file: 'dentist-en/index.html',
    insertBefore: '<section class="section" id="method">',
    lang: 'en', sectorColor: '#1a73e8', bgColor: '#f0f4ff', badgeBg: '#e8eeff',
    pinColor: '#1a73e8', btnBg: '#e8f0fe',
    badgeLabel: 'Google Ads · Live Preview',
    hookLine1: 'This is what your potential patient sees',
    hookLine2: 'when they search on Google for', hookEm: 'dentist Rome',
    hookSub: 'Your competitors already have their ad running. Your practice could appear in the top position starting tomorrow.',
    searchQuery: 'dentist near me Rome',
    bizUrl: 'www.ferrettidental.it',
    headline: 'Ferretti Dental Studio – Award-Winning Dentistry',
    rating: 4.9, ratingDisplay: '4.9', reviewCount: '127 reviews',
    desc: 'Professional dental care in Rome Prati. Free first consultation — book online in under 60 seconds.',
    sitelinks: ['Free Consultation', 'Implants', 'Teeth Whitening', 'Book Online'],
    org1url: 'www.dentist-rome.it', org1title: 'Dentist Rome – Dental Associates', org1desc: 'Dental care in Rome. Free online quotes...',
    org2url: 'www.romadental.com', org2title: 'Rome Dental Clinic – Book Now', org2desc: 'Dental studio in the Prati area of Rome...',
    mapBizName: 'Ferretti Dental Studio', mapCategory: 'Dentist · <span style="color:#188038">Open</span> · Closes at 7:00 PM',
    mapReviewLabel: '(127 reviews)', mapAddr: 'Via Cola di Rienzo 45, Rome',
    closingH: 'Your dental practice could appear here.',
    closingP: 'We set everything up — you focus on your patients.',
    ctaText: 'Book a free call →',
  },
  {
    file: 'restaurant/index.html',
    insertBefore: '<section class="section" id="metodo"><div class="container">',
    lang: 'en', sectorColor: '#e8471a', bgColor: '#fff4f0', badgeBg: '#fde8e0',
    pinColor: '#e8471a', btnBg: '#fde8e0',
    badgeLabel: 'Google Ads · Live Preview',
    hookLine1: 'This is what your potential customer sees',
    hookLine2: 'when they search on Google for', hookEm: 'restaurant Milan',
    hookSub: 'Your competitors are already taking bookings from your potential customers. Your restaurant could appear here starting tomorrow.',
    searchQuery: 'restaurant Milan Navigli',
    bizUrl: 'www.sergiostrattoria.it',
    headline: "Sergio's Trattoria – Authentic Milanese Cuisine",
    rating: 4.7, ratingDisplay: '4.7', reviewCount: '204 reviews',
    desc: "Traditional Italian restaurant in Milan's Navigli district. Book your table online — tasting menu available every evening.",
    sitelinks: ['Book a Table', "Today's Menu", 'Private Room', 'Find Us'],
    org1url: 'www.navigli-restaurants.it', org1title: 'Navigli Restaurants Milan – Top Picks', org1desc: 'Discover the best restaurants in Navigli...',
    org2url: 'www.milanfood.com', org2title: 'Milan Dining – Traditional Cuisine', org2desc: 'Top Milanese restaurants. Book now...',
    mapBizName: "Sergio's Trattoria", mapCategory: 'Restaurant · <span style="color:#188038">Open</span> · Closes at 11:00 PM',
    mapReviewLabel: '(204 reviews)', mapAddr: 'Via dei Navigli 18, Milan',
    closingH: 'Your restaurant could appear here.',
    closingP: 'We set everything up — you focus on the tables.',
    ctaText: 'Book a free call →',
  },
  {
    file: 'lawyers/index.html',
    insertBefore: '<section class="section method" id="method">',
    lang: 'en', sectorColor: '#1a237e', bgColor: '#f0f1ff', badgeBg: '#e8eaff',
    pinColor: '#1a237e', btnBg: '#e8eaff',
    badgeLabel: 'Google Ads · Live Preview',
    hookLine1: 'This is what your potential client sees',
    hookLine2: 'when they search on Google for', hookEm: 'lawyer Turin',
    hookSub: 'Your competitors are already receiving enquiries from your potential clients. Your firm could appear at the top starting tomorrow.',
    searchQuery: 'divorce lawyer Turin',
    bizUrl: 'www.marchettilaw.it',
    headline: 'Marchetti Law – Family Law Specialists Turin',
    rating: 4.8, ratingDisplay: '4.8', reviewCount: '89 reviews',
    desc: 'Divorce, separation and child custody in Turin. Free 30-min consultation — family law specialists since 2001.',
    sitelinks: ['Free Consultation', 'Divorce', 'Child Custody', 'Contact Us'],
    org1url: 'www.lawyer-turin.it', org1title: 'Lawyers Turin – Legal Associates', org1desc: 'Law firms in Turin. Online consultations...',
    org2url: 'www.legal-turin.com', org2title: 'Turin Legal Studio – Civil Law', org2desc: 'Professional legal advice in Turin...',
    mapBizName: 'Marchetti Law Firm', mapCategory: 'Law Firm · <span style="color:#188038">Open</span> · Closes at 6:30 PM',
    mapReviewLabel: '(89 reviews)', mapAddr: 'Corso Vittorio Emanuele II 112, Turin',
    closingH: 'Your law firm could appear here.',
    closingP: 'We set everything up — you focus on your clients.',
    ctaText: 'Book a free call →',
  },
  {
    file: 'gym/index.html',
    insertBefore: '<section class="section method" id="method">',
    lang: 'en', sectorColor: '#7b1fa2', bgColor: '#f9f0ff', badgeBg: '#f3e5ff',
    pinColor: '#7b1fa2', btnBg: '#f3e5ff',
    badgeLabel: 'Google Ads · Live Preview',
    hookLine1: 'This is what your potential member sees',
    hookLine2: 'when they search on Google for', hookEm: 'gym Florence',
    hookSub: 'Your competitors are already signing up new members. Your gym could appear in the top position starting tomorrow.',
    searchQuery: 'gym Florence city centre',
    bizUrl: 'www.fitcenter-florence.it',
    headline: 'FitCenter Florence – Train in the Historic Centre',
    rating: 4.6, ratingDisplay: '4.6', reviewCount: '312 reviews',
    desc: 'Fully equipped gym in Florence City Centre. 7-day free trial — personal trainer included in your first month.',
    sitelinks: ['7-Day Free Trial', 'Group Classes', 'Personal Trainer', 'Memberships'],
    org1url: 'www.gym-florence.it', org1title: 'Gyms Florence – Classes & Memberships', org1desc: 'Top gyms in Florence city centre...',
    org2url: 'www.flofit.com', org2title: 'FloFit Florence – Fitness Centre', org2desc: 'Premium fitness club in the heart of Florence...',
    mapBizName: 'FitCenter Florence', mapCategory: 'Gym · <span style="color:#188038">Open</span> · Closes at 10:00 PM',
    mapReviewLabel: '(312 reviews)', mapAddr: 'Via dei Servi 42, Florence',
    closingH: 'Your gym could appear here.',
    closingP: 'We set everything up — you focus on your members.',
    ctaText: 'Book a free call →',
  },
  {
    file: 'beauty/index.html',
    insertBefore: '<section class="section" id="metodo">',
    lang: 'en', sectorColor: '#c2185b', bgColor: '#fff0f5', badgeBg: '#ffe8f1',
    pinColor: '#c2185b', btnBg: '#ffe8f1',
    badgeLabel: 'Google Ads · Live Preview',
    hookLine1: 'This is what your potential client sees',
    hookLine2: 'when they search on Google for', hookEm: 'beauty salon Naples',
    hookSub: 'Your competitors already have their ad running. Your beauty centre could appear at the top starting tomorrow.',
    searchQuery: 'beauty salon Naples Chiaia',
    bizUrl: 'www.beautylabchiaia.it',
    headline: 'Beauty Lab Chiaia – Facial & Body Treatments',
    rating: 4.8, ratingDisplay: '4.8', reviewCount: '178 reviews',
    desc: 'Beauty centre in Naples Chiaia. Facials, laser hair removal and massages — book online in just 2 minutes.',
    sitelinks: ['Book Now', 'Laser Hair Removal', 'Facial Treatments', 'Price List'],
    org1url: 'www.beauty-naples.it', org1title: 'Beauty Salons Naples – Top Rated', org1desc: 'Best beauty centres in Naples with reviews...',
    org2url: 'www.chiaia-beauty.com', org2title: 'Beauty Center Chiaia – Treatments', org2desc: 'Aesthetic treatments in the heart of Naples...',
    mapBizName: 'Beauty Lab Chiaia', mapCategory: 'Beauty Salon · <span style="color:#188038">Open</span> · Closes at 8:00 PM',
    mapReviewLabel: '(178 reviews)', mapAddr: 'Via Chiaia 88, Naples',
    closingH: 'Your beauty centre could appear here.',
    closingP: 'We set everything up — you focus on your clients.',
    ctaText: 'Book a free call →',
  },
  {
    file: 'physiotherapy/index.html',
    insertBefore: '<section class="section" id="metodo"><div class="container">',
    lang: 'en', sectorColor: '#00796b', bgColor: '#f0faf8', badgeBg: '#e0f5f3',
    pinColor: '#00796b', btnBg: '#e0f5f3',
    badgeLabel: 'Google Ads · Live Preview',
    hookLine1: 'This is what your potential patient sees',
    hookLine2: 'when they search on Google for', hookEm: 'physiotherapist Milan',
    hookSub: 'Your competitors are already receiving new bookings. Your practice could appear in the top position starting tomorrow.',
    searchQuery: 'physiotherapist Milan Brera',
    bizUrl: 'www.fisiobrera.it',
    headline: 'Fisio Brera – Physiotherapy & Osteopathy Milan',
    rating: 4.9, ratingDisplay: '4.9', reviewCount: '94 reviews',
    desc: 'Physiotherapy, osteopathy and rehabilitation in Milan Brera. First session discounted — book online today.',
    sitelinks: ['Discounted First Session', 'Osteopathy', 'Rehabilitation', 'Book Online'],
    org1url: 'www.physio-milan.it', org1title: 'Physiotherapy Milan – Specialist Studio', org1desc: 'Physiotherapists in Milan with online booking...',
    org2url: 'www.brera-health.com', org2title: 'Brera Health – Osteopathy Milan', org2desc: 'Physiotherapy and osteopathy in the city...',
    mapBizName: 'Fisio Brera Studio', mapCategory: 'Physiotherapist · <span style="color:#188038">Open</span> · Closes at 7:00 PM',
    mapReviewLabel: '(94 reviews)', mapAddr: 'Corso Garibaldi 78, Milan',
    closingH: 'Your practice could appear here.',
    closingP: 'We set everything up — you focus on your patients.',
    ctaText: 'Book a free call →',
  },
  {
    file: 'real-estate/index.html',
    insertBefore: '<section class="section method" id="method">',
    lang: 'en', sectorColor: '#f57f17', bgColor: '#fffaf0', badgeBg: '#fff3e0',
    pinColor: '#f57f17', btnBg: '#fff3e0',
    badgeLabel: 'Google Ads · Live Preview',
    hookLine1: 'This is what your potential client sees',
    hookLine2: 'when they search on Google for', hookEm: 'real estate Venice',
    hookSub: 'Your competitors are already collecting qualified leads. Your agency could appear at the top starting tomorrow.',
    searchQuery: 'real estate agency Venice',
    bizUrl: 'www.immobilvenezia.it',
    headline: 'ImmobilVenezia – Apartments & Villas in Venice',
    rating: 4.8, ratingDisplay: '4.8', reviewCount: '67 reviews',
    desc: 'Real estate agency in Venice since 1998. Buying, selling and renting — free property valuation included.',
    sitelinks: ['Free Valuation', 'Apartments', 'Luxury Villas', 'About Us'],
    org1url: 'www.venice-property.it', org1title: 'Venice Property – Buy & Rent', org1desc: 'Real estate listings in Venice...',
    org2url: 'www.venetohomes.com', org2title: 'Veneto Homes – Real Estate', org2desc: 'Apartments and villas in Venice and Mestre...',
    mapBizName: 'ImmobilVenezia Realty', mapCategory: 'Real Estate Agency · <span style="color:#188038">Open</span> · Closes at 6:00 PM',
    mapReviewLabel: '(67 reviews)', mapAddr: 'Campo San Luca 4516, Venice',
    closingH: 'Your agency could appear here.',
    closingP: 'We set everything up — you focus on your listings.',
    ctaText: 'Book a free call →',
  },
  {
    file: 'hotel-en/index.html',
    insertBefore: '<section class="section" id="method">',
    lang: 'en', sectorColor: '#e65100', bgColor: '#fff5f0', badgeBg: '#ffe8d6',
    pinColor: '#e65100', btnBg: '#ffe8d6',
    badgeLabel: 'Google Ads · Live Preview',
    hookLine1: 'This is what your potential guest sees',
    hookLine2: 'when they search on Google for', hookEm: 'hotel Rome',
    hookSub: 'Your competitors are already receiving direct bookings. Your hotel could appear at the top starting tomorrow.',
    searchQuery: 'hotel Rome city centre',
    bizUrl: 'www.foriimperialihotel.it',
    headline: 'Fori Imperiali Hotel – In the Heart of Rome',
    rating: 4.7, ratingDisplay: '4.7', reviewCount: '521 reviews',
    desc: '4-star hotel in Rome City Centre. Breakfast included, free WiFi — book directly and save 20% on your stay.',
    sitelinks: ['Book Direct', 'Special Offers', 'Rooms & Rates', 'Find Us'],
    org1url: 'www.hotel-rome-centre.it', org1title: 'Hotels Rome Centre – Best Rates', org1desc: 'Top hotels in central Rome. Best price guarantee...',
    org2url: 'www.romeaccommodation.com', org2title: 'Rome Hotels – Book with Confidence', org2desc: 'Hotels in Rome with breakfast included...',
    mapBizName: 'Fori Imperiali Hotel', mapCategory: 'Hotel ★★★★ · <span style="color:#188038">Open</span> · 24-hour Reception',
    mapReviewLabel: '(521 reviews)', mapAddr: 'Via dei Fori Imperiali 15, Rome',
    closingH: 'Your hotel could appear here.',
    closingP: 'We set everything up — you focus on hospitality.',
    ctaText: 'Book a free call →',
  },
  {
    file: 'plumber/index.html',
    insertBefore: '<section class="section" id="metodo"><div class="container">',
    lang: 'en', sectorColor: '#2e7d32', bgColor: '#f0f7f0', badgeBg: '#e8f5e9',
    pinColor: '#2e7d32', btnBg: '#e8f5e9',
    badgeLabel: 'Google Ads · Live Preview',
    hookLine1: 'This is what your potential client sees',
    hookLine2: 'when they search on Google for', hookEm: 'plumber Bologna',
    hookSub: 'Your competitors are already receiving calls from your potential customers. Your business could appear at the top starting tomorrow.',
    searchQuery: 'emergency plumber Bologna',
    bizUrl: 'www.bolognaplumbing.it',
    headline: 'Bologna Plumbing Pro – 30-Min Emergency Response',
    rating: 4.9, ratingDisplay: '4.9', reviewCount: '156 reviews',
    desc: 'Leaks, blockages and boilers in Bologna. Available 24/7 — free instant quote, no hidden charges.',
    sitelinks: ['Call Now', '24/7 Emergencies', 'Free Quote', 'Service Area'],
    org1url: 'www.plumber-bologna.it', org1title: 'Plumbers Bologna – Emergency Service', org1desc: 'Plumbers in Bologna available 24 hours...',
    org2url: 'www.bologna-pipework.com', org2title: 'Bologna Pipework – Fast Response', org2desc: 'Plumbing repairs and installations...',
    mapBizName: 'Bologna Plumbing Pro', mapCategory: 'Plumber · <span style="color:#188038">Open</span> · Available 24/7',
    mapReviewLabel: '(156 reviews)', mapAddr: 'Via Zamboni 22, Bologna',
    closingH: 'Your business could appear here.',
    closingP: 'We set everything up — you focus on the work.',
    ctaText: 'Book a free call →',
  },
];

let successCount = 0;
let errorCount = 0;

for (const page of pages) {
  const filePath = resolve(ROOT, page.file);
  let html;
  try {
    html = readFileSync(filePath, 'utf8');
  } catch (e) {
    console.error(`SKIP (read error): ${page.file} — ${e.message}`);
    errorCount++;
    continue;
  }

  if (!html.includes(page.insertBefore)) {
    console.error(`SKIP (marker not found): ${page.file} — "${page.insertBefore}"`);
    errorCount++;
    continue;
  }

  if (html.includes('ads-showcase-grid')) {
    console.log(`SKIP (already has section): ${page.file}`);
    continue;
  }

  const section = buildSection(page);
  const updated = html.replace(page.insertBefore, section + page.insertBefore);

  try {
    writeFileSync(filePath, updated, 'utf8');
    console.log(`OK: ${page.file}`);
    successCount++;
  } catch (e) {
    console.error(`SKIP (write error): ${page.file} — ${e.message}`);
    errorCount++;
  }
}

console.log(`\nDone: ${successCount} updated, ${errorCount} errors.`);
